; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.23506.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\Ashwin\AppData\Local\Temp\.NETFramework,Version=v4.6.1.AssemblyAttributes.cpp"
